<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>eef28902-4deb-42e3-ac1f-6e5a061c1d6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cartur']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;cartur&quot;)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cartur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fbc63dde-a239-4fe6-8013-e26d062ec2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>6a933830-3cbe-49ea-967d-b2ca39e78d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartur</value>
      <webElementGuid>fdc955d0-d6aa-458f-92a7-4f6779fbe73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cart.html</value>
      <webElementGuid>98a848f9-51aa-481c-b0a4-6552029511d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>6c54ce51-d698-4268-b5d6-6d3254df92f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartur&quot;)</value>
      <webElementGuid>5c7d4cac-8b02-48ad-9720-fb30578e58ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cartur']</value>
      <webElementGuid>ddd33f43-1f57-4f5a-b036-ebb858f95a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarExample']/ul/li[4]/a</value>
      <webElementGuid>6ac93130-43d8-4b86-8742-3d692c817c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cart')]</value>
      <webElementGuid>d3e2fe50-180a-44c4-9156-5384330cf758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cart.html')]</value>
      <webElementGuid>e429d320-5003-45b3-827a-7b7b48ba1f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>fa53bb76-2849-4082-b694-3808294d81d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cartur' and @href = 'cart.html' and (text() = 'Cart' or . = 'Cart')]</value>
      <webElementGuid>c8c84e69-a086-4844-889c-bb8ae83d2568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
